### ISSUE TITLE
I get this error on two different servers when I run this script

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [vertelab/odootools#4]
Building wheels for collected packages: lxml, Mako, Pillow, psutil, psycopg2, python-ldap, reportlab
  Building wheel for lxml (setup.py) ... \

/SOLVED: By adding more 4 GB memory and 2 Processors to the server.

**Comment by fredrikarvas-vertel** [comment]
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-81-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Sun Aug 22 07:43:17 2021 from 188.149.152.135
verified_root@verified-email-prod1:~$ wget -O- https://raw.githubusercontent.com                                                                                                 /vertelab/odootools/13.0/install | bash
--2021-08-22 08:05:28--  https://raw.githubusercontent.com/vertelab/odootools/13                                                                                                 .0/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.1                                                                                                 33, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.                                                                                                 133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4955 (4.8K) [text/plain]
Saving to: ‘STDOUT’

-                   100%[===================>]   4.84K  --.-KB/s    in 0s

2021-08-22 08:05:28 (62.2 MB/s) - written to stdout [4955/4955]

Performing basic prerequisite checks ...
Preparing to install Odoo
Odoo already installed.
Installing other dependencies and packages
Installing for Ubuntu 20.04
Installing additional packages
[sudo] password for verified_root:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libjpeg-dev is already the newest version (8c-2ubuntu8).
libsasl2-dev is already the newest version (2.1.27+dfsg-2).
libxslt1-dev is already the newest version (1.1.34-4).
python3-dev is already the newest version (3.8.2-0ubuntu2).
python3-setuptools is already the newest version (45.2.0-1).
wget is already the newest version (1.20.3-1ubuntu1).
libzip-dev is already the newest version (1.5.1-0ubuntu1).
node-less is already the newest version (1.6.3~dfsg-3).
python3-venv is already the newest version (3.8.2-0ubuntu2).
python3-wheel is already the newest version (0.34.2-1).
build-essential is already the newest version (12.8ubuntu1.1).
git is already the newest version (1:2.25.1-1ubuntu3.1).
libldap2-dev is already the newest version (2.4.49+dfsg-2ubuntu1.8).
libpq-dev is already the newest version (12.8-0ubuntu0.20.04.1).
python3-pip is already the newest version (20.0.2-5ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Installing Python modules
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
--2021-08-22 08:05:39--  https://raw.githubusercontent.com/odoo/odoo/13.0/requir                                                                                                 ements.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.1                                                                                                 33, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.                                                                                                 133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1358 (1.3K) [text/plain]
Saving to: ‘/tmp/requirements.txt’

/tmp/requirements.t 100%[===================>]   1.33K  --.-KB/s    in 0s

2021-08-22 08:05:39 (55.6 MB/s) - ‘/tmp/requirements.txt’ saved [1358/1358]

Ignoring gevent: markers 'sys_platform != "win32" and python_version < "3.7"' don't match your environment
Ignoring gevent: markers 'sys_platform == "win32" and python_version < "3.7"' don't match your environment
Ignoring greenlet: markers 'python_version < "3.7"' don't match your environment
Ignoring lxml: markers 'sys_platform != "win32" and python_version < "3.7"' don't match your environment
Ignoring lxml: markers 'sys_platform == "win32"' don't match your environment
Ignoring Pillow: markers 'sys_platform == "win32" and python_version >= "3.7"' don't match your environment
Ignoring psycopg2: markers 'sys_platform != "win32" and python_version < "3.8"' don't match your environment
Ignoring Werkzeug: markers 'sys_platform == "win32"' don't match your environment
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: Babel==2.6.0 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: decorator==4.3.0 in /usr/local/lib/python3.8/dist-packages (from -r /tmp/requirements.txt (line 3)) (4.3.0)
Requirement already satisfied: docutils==0.14 in /usr/local/lib/python3.8/dist-packages (from -r /tmp/requirements.txt (line 4)) (0.14)
Processing /root/.cache/pip/wheels/1a/77/81/e8be55a2437aaf71d7b757645f396ac0cc956299b77b267f29/ebaysdk-2.1.5-py3-none-any.whl
Requirement already satisfied: feedparser==5.2.1 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 6)) (5.2.1)
Collecting gevent==1.5.0
  Using cached gevent-1.5.0-cp38-cp38-manylinux2010_x86_64.whl (5.9 MB)
Requirement already satisfied: greenlet==0.4.15 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 11)) (0.4.15)
Collecting html2text==2018.1.9
  Using cached html2text-2018.1.9-py3-none-any.whl (21 kB)
Requirement already satisfied: Jinja2==2.10.1 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 13)) (2.10.1)
Processing /root/.cache/pip/wheels/16/7c/c8/e031d76322d8f17dc1193074755b727348d944f551ef0132a4/libsass-0.17.0-cp38-cp38-linux_x86_64.whl
Collecting lxml==4.3.2
  Using cached lxml-4.3.2.tar.gz (4.4 MB)
Processing /root/.cache/pip/wheels/93/99/ee/af392bd8ad21f5672c456c06724f225c2df8284e285c8a0beb/Mako-1.0.7-py3-none-any.whl
Requirement already satisfied: MarkupSafe==1.1.0 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 19)) (1.1.0)
Collecting mock==2.0.0
  Using cached mock-2.0.0-py2.py3-none-any.whl (56 kB)
Collecting num2words==0.5.6
  Using cached num2words-0.5.6-py2.py3-none-any.whl (64 kB)
Requirement already satisfied: ofxparse==0.19 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 22)) (0.19)
Collecting passlib==1.7.1
  Using cached passlib-1.7.1-py2.py3-none-any.whl (498 kB)
Processing /root/.cache/pip/wheels/5f/a8/6b/5b7b3f764d879214eb03570f74d2b086201eb514e6ffa68d6d/Pillow-5.4.1-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: polib==1.1.0 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 26)) (1.1.0)
Processing /root/.cache/pip/wheels/79/67/93/91114b71e0965edb6233d607d82bb5de75ad02e3d9d469ba17/psutil-5.6.6-cp38-cp38-linux_x86_64.whl
Processing /root/.cache/pip/wheels/9c/f4/9e/329d4de5959958bf6cf7db89d6bc9adbf3903dc1a52c651162/psycopg2-2.8.3-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: pydot==1.4.1 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 30)) (1.4.1)
Processing /root/.cache/pip/wheels/a6/4c/bf/af9919d33e2192f2da93df81bd995ec474b6d24acfbff19033/python_ldap-3.1.0-cp38-cp38-linux_x86_64.whl
Collecting pyparsing==2.2.0
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: PyPDF2==1.26.0 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 33)) (1.26.0)
Requirement already satisfied: pyserial==3.4 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 34)) (3.4)
Requirement already satisfied: python-dateutil==2.7.3 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 35)) (2.7.3)
Collecting pytz==2019.1
  Using cached pytz-2019.1-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: pyusb==1.0.2 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 37)) (1.0.2)
Requirement already satisfied: qrcode==6.1 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 38)) (6.1)
Processing /root/.cache/pip/wheels/4c/ea/d3/598906da51f4963e626b350703d80226bd8fbcccdc4ffd776c/reportlab-3.5.13-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: requests==2.21.0 in /usr/local/lib/python3.8/dist-packages (from -r /tmp/requirements.txt (line 40)) (2.21.0)
Collecting zeep==3.2.0
  Using cached zeep-3.2.0-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: vatnumber==1.2 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 42)) (1.2)
Requirement already satisfied: vobject==0.9.6.1 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 43)) (0.9.6.1)
Collecting Werkzeug==0.14.1
  Using cached Werkzeug-0.14.1-py2.py3-none-any.whl (322 kB)
Requirement already satisfied: XlsxWriter==1.1.2 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 46)) (1.1.2)
Collecting xlwt==1.3.*
  Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Requirement already satisfied: xlrd==1.1.0 in /usr/lib/python3/dist-packages (from -r /tmp/requirements.txt (line 48)) (1.1.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from libsass==0.17.0->-r /tmp/requirements.txt (line 14)) (1.14.0)
Requirement already satisfied: pbr>=0.11 in /usr/lib/python3/dist-packages (from mock==2.0.0->-r /tmp/requirements.txt (line 20)) (5.4.5)
Requirement already satisfied: pyasn1-modules>=0.1.5 in /usr/lib/python3/dist-packages (from python-ldap==3.1.0->-r /tmp/requirements.txt (line 31)) (0.2.1)
Requirement already satisfied: pyasn1>=0.3.7 in /usr/lib/python3/dist-packages (from python-ldap==3.1.0->-r /tmp/requirements.txt (line 31)) (0.4.2)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests==2.21.0->-r /tmp/requirements.txt (line 40)) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.21.0->-r /tmp/requirements.txt (line 40)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.21.0->-r /tmp/requirements.txt (line 40)) (2019.11.28)
Requirement already satisfied: attrs>=17.2.0 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r /tmp/requirements.txt (line 41)) (19.3.0)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r /tmp/requirements.txt (line 41)) (1.4.3)
Requirement already satisfied: defusedxml>=0.4.1 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r /tmp/requirements.txt (line 41)) (0.6.0)
Requirement already satisfied: isodate>=0.5.4 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r /tmp/requirements.txt (line 41)) (0.6.0)
Requirement already satisfied: requests-toolbelt>=0.7.1 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r /tmp/requirements.txt (line 41)) (0.8.0)
Requirement already satisfied: cached-property>=1.3.0 in /usr/lib/python3/dist-packages (from zeep==3.2.0->-r /tmp/requirements.txt (line 41)) (1.5.1)
Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... -

**Comment by fredrikarvas-vertel** [comment]
Now with an error message:


Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c2qhmrdv/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c2qhmrdv/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qwfwapgw
       cwd: /tmp/pip-install-c2qhmrdv/lxml/
  Complete output (84 lines):
  Building lxml version 4.3.2.
  Building without Cython.
  Using build configuration of libxslt 1.1.34
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-3.8/lxml
  creating build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-3.8/lxml/includes
  creating build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-3.8/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-3.8/lxml/html
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-3.8/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-3.8/lxml
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-3.8/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-3.8/lxml/includes
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  creating build/temp.linux-x86_64-3.8/src/lxml
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/include/python3.8 -c src/lxml/etree.c -o build/temp.linux-x86_64-3.8/src/lxml/etree.o -w
  x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
  compilation terminated.
  Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitm41kc2f1.c -o tmp/xmlXPathInitm41kc2f1.o
  cc tmp/xmlXPathInitm41kc2f1.o -lxml2 -o a.out
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, ebaysdk, gevent, html2text, libsass, Mako, mock, num2words, passlib, Pillow, psutil, psycopg2, python-ldap, pyparsing, pytz, reportlab, zeep, Werkzeug, xlwt
  Attempting uninstall: lxml
    Found existing installation: lxml 4.5.0
    Not uninstalling lxml at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'lxml'. No files were found to uninstall

**Comment by anderswallenquist** [comment]
I have now tested this on two Ubuntu 20.04 servers without an error.

    wget -O /tmp/requirements.txt https://raw.githubusercontent.com/odoo/odoo/13.0/requirements.txt
    sudo -H pip3 install -r /tmp/requirements.txt
    
 It is the requirement.txt for Odoo 13 that Odoo publish on their github. I can find a change in this file made nine month ago when you are using python < 3.7. You should have python 3.8.10 using Ubuntu 20.04.

Can it be a local error (failed with exit status 1 creating tmp)? disk full or other thing?

If the error still remains i will create a vanilla 20.04 and do antoher test,

**Comment by fredrikarvas-vertel** [comment]
Thanks: 
I have  Python 3.8.10

In terms of memory I have:
verified_root@verified-email-prod2:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            910         153         329          12         426         584
Swap:             0           0           0

**Comment by fredrikarvas-vertel** [comment]
I Increased the RAM and Processors and it worked fine.
